### ISSUE TITLE
will have support for other languages?

### ISSUE THREAD

**Issue by N0tvich** [stantanasi/sflix#1]
I tried it and if I could enjoy it there are movies that have subtitles and it's good but I would like to know if you have thought of making it in several languages ​​or will you only leave it in English

excellent project I hope you don't abandon it👌

**Comment by stantanasi** [comment]
**It's not my priority.** Currently I only use [sflix.to](https://sflix.to) website to retrieve movies and TV shows, which is an English website supporting only original audio with multilingual subtitles.

I plan to add multiple providers soon, like [CloudStream](https://github.com/recloudstream/cloudstream) does. I don't know yet which website I will implement next.
When it will be possible to add providers easily, I will probably implement several languages, but you will have to wait a little longer before seeing this feature implemented. 🙂

Thank you a lot, I don't intend to abandon it until it's fully functional! 🤝

**Comment by stantanasi** [comment]
Hi @N0tvich, it is now possible to choose between several providers in the app. I will soon implement support for other languages.
Which languages would you like to see supported by the app first? And do you have a streaming website for that language?
