### ISSUE TITLE
Change provider without exiting the app

### ISSUE THREAD

**Issue by ajimal173** [stantanasi/sflix#15]
### Summary

app working fine n good but i didnt find continue to watch tab. 
sflix works smooth n good. 

#### suggestion:
its just a suggestion to choose n change provider without exit from app. 

#### note:
all movies provider home tab not loading, othertabs movies and series working good

#### request:
implement anime series and movies content to watch with English subtitle. (if possible)

---

thank u very much for ur service n best quality provider which u chosen....

### Please confirm the following

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by stantanasi** [comment]
> #### suggestion:
> its just a suggestion to choose n change provider without exit from app.

I also think it would be a nice feature to be able to switch providers from within the app, instead of having to leave it.
But this functionality is not a priority at all and I still have to think about how to implement it well.

**Comment by stantanasi** [comment]
> #### note:
> all movies provider home tab not loading, othertabs movies and series working good

The AllMoviesForYou provider sometimes takes a long time to load, I need to take a look at this issue.

**Comment by stantanasi** [comment]
> #### request:
> implement anime series and movies content to watch with English subtitle. (if possible)

If the subtitles are not available on the provider, there is nothing I can do to add them.
However, if the subtitles are available on the provider's site but not on my app, could you provide which films or episodes of series are available with subtitles?

**Comment by ajimal173** [comment]
sure okay sir. let me check n let u know by today

**Comment by Farid001979** [comment]
Can you add Arabic subtitles please

**Comment by stantanasi** [comment]
**Available on [Release 1.3.0](https://github.com/stantanasi/sflix/releases/latest)**
