### ISSUE TITLE
Add the ability to change video player or adjust the resolution

### ISSUE THREAD

**Issue by Pluncidelst** [stantanasi/sflix#18]
### Summary

Thank you for creating this app, it's awesome. It would be nice if we could favorite tv shows, adjust resolution or use an external player.

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by stantanasi** [comment]
Sorry for taking so much time on this issue. I'm currently working on it, it should be finished in 1-2 weeks.

**Comment by stantanasi** [comment]
**Available on [Release 1.3.0](https://github.com/stantanasi/sflix/releases/latest)**
