### ISSUE TITLE
please implement tmdb

### ISSUE THREAD

**Issue by madrid2022ok** [stantanasi/sflix#19]
### Summary

tmdb api could be implemented in sflix app movie series

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by stantanasi** [comment]
**Probably not a good idea to implement [TMDb API](https://developers.themoviedb.org/3).**

The implementation of the TMDb API means that to retrieve the movie/series data, the application will have to request two websites (the selected provider + TMDb). It will increase the loading time and it might be annoying.
Also TMDb have movies/series/episodes unreleased or not available on streaming providers, so the app will display unwatchable movies and series, also annoying!

**Comment by oathzed** [comment]
> **Probably not a good idea to implement [TMDb API](https://developers.themoviedb.org/3).**
> 
> The implementation of the TMDb API means that to retrieve the movie/series data, the application will have to request two websites (the selected provider + TMDb). It will increase the loading time and it might be annoying. Also TMDb have movies/series/episodes unreleased or not available on streaming providers, so the app will display unwatchable movies and series, also annoying!

its good for reliability though, if the sflix site ever goes down, what will happen? this is why a extension system is better. and you can make it not show unreleased episodes

**Comment by stantanasi** [comment]
> its good for reliability though, if the sflix site ever goes down, what will happen?

If the SFlix site goes down, the application is unusable like the website because it will be impossible to watch anything. If I implement TMDb, then yes, the app will be functional and the user will be able to navigate the app properly, but it still be impossible to watch anything (TMDb does not provide free streaming services).
Personally, it would annoy me to navigate through the entire app, only to realize at the end that it's impossible to watch anything.
TMDb is only useful for displaying more pictures and information about movies/tv shows/episodes.

> in short, you wouldn't be requesting the website and TMDB you would just be requesting TMDB, and when you press play you would only request the sources from a website.

Even if I manage to get the correct ID of the movie from the site by searching for the title (which already seems impossible depending on some sites). If the website is not working then it will also be impossible to watch the movie.

**Comment by oathzed** [comment]
> > its good for reliability though, if the sflix site ever goes down, what will happen?
> 
> If the SFlix site goes down, the application is unusable like the website because it will be impossible to watch anything. If I implement TMDb, then yes, the app will be functional and the user will be able to navigate the app properly, but it still be impossible to watch anything (TMDb does not provide free streaming services). Personally, it would annoy me to navigate through the entire app, only to realize at the end that it's impossible to watch anything. TMDb is only useful for displaying more pictures and information about movies/tv shows/episodes.
> 
> > in short, you wouldn't be requesting the website and TMDB you would just be requesting TMDB, and when you press play you would only request the sources from a website.
> 
> Even if I manage to get the correct ID of the movie from the site by searching for the title (which already seems impossible depending on some sites). If the website is not working then it will also be impossible to watch the movie.

Sorastream, an addon from cloudstream uses TMDB for the data part and has multiple sources for streaming, I've never noticed anything I've tried watching have no links, it has 20 links at least for each thing. You should check it out

**Comment by stantanasi** [comment]
Okay thanks I will look into it.
If it's better and not too difficult to implement, I will integrate it.
