### ISSUE TITLE
App installed but not working on my smartphone

### ISSUE THREAD

**Issue by MrConqueror** [stantanasi/sflix#2]
I installed the app but i can't open it

**Comment by stantanasi** [comment]
@MrConqueror Could you tell me what device are you using with what version of Android? Also can you send me a tutorial on how you do it to install the app, I will follow the same method?

Can you check into the Settings > Apps > See All Apps, if the app is well installed and you can open it.

**Comment by MrConqueror** [comment]
> @MrConqueror Could you tell me what device are you using with what version of Android? Also can you send me a tutorial on how you do it to install the app, I will follow the same method?
> 
> Can you check into the Settings > Apps > See All Apps, if the app is well installed and you can open it.

Poco X3 GT and i think this is Android 12. I just install the app like normal person LOL

**Comment by stantanasi** [comment]
The app is **only compatible on Android TV**, on devices such as Chromecast with Google TV, Amazon Fire TV Stick, or smart TVs. 
It's not supported on Android smartphone.

If you know how to use Android Studio, you could replace `true` by `false` on this line:
https://github.com/stantanasi/sflix/blob/e4bf1b0906137b36b2c02dfc18724a5f31f7c343/app/src/main/AndroidManifest.xml#L12
By setting `required="false"`, you will be able launch the app on your Android smartphone.

But I have to warn you that the app is not optimized for small touchscreens, so you may have some difficulty navigating through movies and TV shows.
