### ISSUE TITLE
request to add genre and country option in app

### ISSUE THREAD

**Issue by ajimal173** [stantanasi/sflix#20]
### Summary

dear admin,

here i request u to add filter option in app with search content by "genre" and "country"

genre option already available in site hereby i share the image pls do the need implement filter option in search or separate button for the genre and country.

pls add the "genre and country" option in next update if possible

with regards
AJIMALKHAN

![image](https://user-images.githubusercontent.com/5946980/213844782-53f7bb77-856b-4fa1-9987-360452bfe081.png)

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by stantanasi** [comment]
Hey @ajimal173, I will now implement this feature.
Do you have any idea where I could display this filter?

**Comment by stantanasi** [comment]
Hey @ajimal173, do you have an idea where I could put this functionality inside the app?

**Comment by DarkCrypt** [comment]
Idk if you like these possible ideas but this is what I thought of at the moment. The top bar is meant to be above the displayed results and has more options than initial post. Or maybe a few options could be implemented in the left menu toward the bottom. See screenshot.

<img width="960" alt="Screenshot_Menu_Placement" src="https://user-images.githubusercontent.com/121076677/226156833-824e4e56-9e8f-4243-9314-cca8abff6544.png">

**Comment by DarkCrypt** [comment]
Nice! By implementing in search page you will be able to utilize the empty space under the search bar. That'll be awesome and I like that much better than my previous comment.

**Comment by ajimal173** [comment]
thank u sir

waiting for the app

**Comment by stantanasi** [comment]
**Available on [Release 1.3.1](https://github.com/stantanasi/sflix/releases/latest)**

![image](https://user-images.githubusercontent.com/46174829/229518621-f5fef60f-5fc5-4f80-ba7e-c2eadb03a997.png)

**Comment by ajimal173** [comment]
dear admin,

thanks a lot let me install this in my tv

once again thank u

**Comment by DarkCrypt** [comment]
This turned out wonderful, nice work!

**Comment by ajimal173** [comment]
Glad you liked it!
