### ISSUE TITLE
It gives error when you play anything

### ISSUE THREAD

**Issue by Rohailmirza00** [stantanasi/sflix#21]
### Description

It was working fine before but it gives error whenever you play anything. What’s the issue?

### Reproduction steps

Error

### Operating system

Tcl androit tv. Android 11

### App version

v1.2.1 (Latest)

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If related to a provider, I have checked the site and it works, but not the app.

**Comment by Rohailmirza00** [comment]
Solved

**Comment by stantanasi** [comment]
**Fix on [Release 1.3.0](https://github.com/stantanasi/sflix/releases/latest)**
