### ISSUE TITLE
In App Updater

### ISSUE THREAD

**Issue by DarkCrypt** [stantanasi/sflix#22]
### Summary

Because this app is an Android Tv build and also because of your continuously growing user base, an in app updater would be a very helpful feature. This makes it easy to update the app with a tv remote and eliminate the need to acquire updates from outside the app.

You could implement a "Settings" option in the menu where an updater could be included and more. See screenshot.

<img width="960" alt="Screenshot_Settings" src="https://user-images.githubusercontent.com/121076677/226156497-70adf196-8fae-4401-8573-c1fba555b5e8.png">

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by stantanasi** [comment]
I don't really know how to implement an in-app updater.
Should I have a button in settings that targets the app's latest APK? Or maybe I need to install a dependency?

If you have any documentation, I'll be glad to get it.

**Comment by DarkCrypt** [comment]
> Should I have a button in settings that targets the app's latest APK? Or maybe I need to install a dependency?

I'm thinking more than likely both. You'll definitely need a download button that targets the latest APK from your Github release page(or any external link). I also think you might need some kind of dependency for this function.

I've been trying to find some kind of documentation or code for implementation. The Android developers website says in-app updates are only supported for Android mobile devices, Android tablets, and Chrome OS devices. Most implementation methods I've read about require Google Play Core libraries and this is completely unacceptable and ridiculous. I know an in-app updater is possible because CloudStream does this and it works great.

With that being said, I did find a few repos on Github that hopefully will help make this feature a reality...

[LocalAppUpdate](https://github.com/mhasancse15/LocalAppUpdate) - Can be used for downloading the Apk from a link, save it to external or internal storage, and then automatic installing of the APK. This repo also has a working demo APK in the app folder which is a good representation of what we're wanting to do.

[In-App-Update-Compose](https://github.com/warting/In-App-Update-Compose) - A way to make in app updates in compose. I didn't see a demo APK.

[CloudStream](https://github.com/recloudstream/cloudstream/blob/0cbee7068326a8f215f53c45d9c85d3601eac468/app/src/main/java/com/lagradost/cloudstream3/utils/InAppUpdater.kt) - This leads to CloudStream's in-app updater file.

If the first 2 repos won't work, CloudStream's example should for sure. At least I'd think so.

**Comment by stantanasi** [comment]
Thanks a lot, I'll look into the repositories you provided.
I think I'll add a download button that targets the latest version/APK first, since that seems easy to do. And then I'll see if it's possible to improve it.

**Comment by DarkCrypt** [comment]
Ok, sounds good. I really appreciate your time, hard work, and dedication to this app. Thank you for being an awesome dev!

**Comment by stantanasi** [comment]
Thank you, it means a lot to me ❤️

**Comment by stantanasi** [comment]
**Should work from [Release 1.3.1](https://github.com/stantanasi/sflix/releases/latest)**, I'll have to check if it works when a new release comes out.

At launch, if a new version is available, a dialog will be displayed proposing the update of the application.
![image](https://user-images.githubusercontent.com/46174829/229519950-20ea1ff7-ee2a-4980-8d9b-223416f1aa93.png)

**Comment by DarkCrypt** [comment]
I installed v1.3.1 and am excited to try this out when a future update is released. The screenshot looks great! For my own curiosity, did the repos I suggested above work for you or did you have to try something different?

**Comment by stantanasi** [comment]
Yep thanks a lot for the repos, I mostly used [CloudStream](https://github.com/recloudstream/cloudstream/blob/0cbee7068326a8f215f53c45d9c85d3601eac468/app/src/main/java/com/lagradost/cloudstream3/utils/InAppUpdater.kt) to implement this functionality. As you can see some similarities in [SFlix's InAppUpdater file](https://github.com/stantanasi/sflix/blob/f9a258d3ba413bc670c634e9488c1c58f567b72b/app/src/main/java/com/tanasi/sflix/utils/InAppUpdater.kt).

**Comment by DarkCrypt** [comment]
Fantastic! I'm so pumped I was able to help in this way! As I look at the differences, you were able to implement this feature with a lot less code as well. I find it very interesting and inspiring that you are a self-taught dev. This is not only impressive but incredible. I think you're doing an amazing job!

**Comment by stantanasi** [comment]
Indeed, they have developed a lot of code for their different versions and features, while I only have to download my latest version and install it.
Thank you so much for your words and encouragement! Being a self-taught developer has been a challenging but rewarding journey for me. It means a lot to hear that my efforts are appreciated. ❤️

**It's never too late to start developing!!**

**Comment by stantanasi** [comment]
It should be possible to update the application to version [1.3.2](https://github.com/stantanasi/streamflix/releases/latest) directly when launching the application.
PS: I decided to change the name of my application. When installing the new version, there will be two apps **StreamFlix** and SFlix, please uninstall the previous app SFlix.

**Comment by stantanasi** [comment]
> Are you planning on changing the logo as well?

I'm planning to change it but I'm not a designer so I don't have any idea 😆. So it could take time until I change it.

**Comment by DarkCrypt** [comment]
I hear that, I'm not a designer either. It could still be a S but what should it look like? Hmm 🤔, if my brain does come up with something I'll let you know.
