### ISSUE TITLE
Have the video player UI fade away in 1 animation faster

### ISSUE THREAD

**Issue by oathzed** [stantanasi/sflix#29]
### Summary

currently it stays on screen for like 8 seconds, it should stay up for maybe 2 or 3 max, and fade off quickly

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by stantanasi** [comment]
Currently player controls remain visible for 5+2 seconds (5 seconds for time and buttons under seek bar + 2 seconds for play/pause button).
It is only possible to reduce the duration of the first one, I will see which duration is the most convenient!

**It is also possible to hide the controls immediately using the back button on the remote.**

**Comment by oathzed** [comment]
Ok awesome sounds good, appreciate it!

**Comment by stantanasi** [comment]
**Available on [Release 1.3.2](https://github.com/stantanasi/streamflix/releases/latest)**
PS: I decided to change the name of my application. When installing the new version, there will be two apps **StreamFlix** and SFlix, please uninstall the previous app SFlix.
