### ISSUE TITLE
Search is not very accurate on how it sorts

### ISSUE THREAD

**Issue by oathzed** [stantanasi/sflix#31]
### Description

Search for "Harry potter", you'll have to scroll down to the 4th row just to start seeing anything that starts with "harry potter"

### Reproduction steps

1. go to search, and search "harry potter"
2. see results
3. scroll down to 4th row, you'll see them there, should be at the top row considering it's the only item that has "harry potter" in it.

### App version

v1.3.1 (Latest)

### Operating system

shield android tv

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If related to a provider, I have checked the site and it works, but not the app.

**Comment by stantanasi** [comment]
I also find it weird how the SFlix website sorts their results, but I'd rather not change it.
It will take me way too much time to improve the search results and sort them out, for something that "works".

[Search Harry Potter](https://sflix.to/search/harry-potter)

**Comment by oathzed** [comment]
Ahh that's true, fair enough
