### ISSUE TITLE
Add Semi Transparent Subtitles 

### ISSUE THREAD

**Issue by AlanAAL** [stantanasi/sflix#37]
### Summary

Hello everyone,
first of all thanks for the amazing Work, i just wanted to share with you my experience, IT IS AMAZING so Far.
i Just i wanted to request a feature where you can change the opacity of the Subtitles Background, it would be amazing to remove that black background and replace it with Semi Transparent (50%) OR LESS
Thanks i Advance

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by oathzed** [comment]
black border to letters would be a better solution

**Comment by AlanAAL** [comment]
Hey, No not really for me it's not. The Semi Transparet border is much much better when watching TV, it would be great if there was an option to activated for those who share my opinion.
Thanks in advance

**Comment by AlanAAL** [comment]
Here a phot describing what i said
https://i.ibb.co/8KSfKHc/page.jpg
Thanks in advance

**Comment by AlanAAL** [comment]
Hey @optzeci see this photo to understand what i'm referring to 👍 :
https://i.ibb.co/8KSfKHc/page.jpg
Thanks for your reply

**Comment by optzeci** [comment]
> Hey @optzeci see this photo to understand what i'm referring to 👍 :
> https://i.ibb.co/8KSfKHc/page.jpg
> Thanks for your reply

I already saw and already know that. That looks ugly, even if it's transparent.

Outlining the letters with black(for which you can choose opacity) it's better, because you can see the subtitles both on dark and light background in a movie. Probably you are not used to this, but believe it's the best thing, because it won't display that rectangle under the subtitles, so you will get to see more of the movie images.

This is what I am talking about

![Screenshot_20230503_164021.jpg](https://user-images.githubusercontent.com/90402533/235951246-eb289cbf-05ed-43c8-b077-d56864ae9f71.jpg)

**Comment by AlanAAL** [comment]
Exactly Man, that's what i was asking, if they can add this option to change the Opacity, so everyone can use the settings that they like
Thanks again

**Comment by stantanasi** [comment]
For now I added a semi-transparent subtitle, because I prefer that too.
But I plan to add settings to customize subtitles for each user!

**Comment by AlanAAL** [comment]
Thanks a lot i'll be waiting for the update
Thanks again

**Comment by stantanasi** [comment]
**Available on [Release 1.3.2](https://github.com/stantanasi/streamflix/releases/latest)**
PS: I decided to change the name of my application. When installing the new version, there will be two apps **StreamFlix** and SFlix, please uninstall the previous app SFlix.

**Comment by AlanAAL** [comment]
i installed the new release, and it's working great, and the subtitles are exactly as i imagined them
Thanks a lot

**Comment by stantanasi** [comment]
You can now customize video's subtitles
**Available on [Release 1.3.4](https://github.com/stantanasi/streamflix/releases/latest)**

[screenshot.webm](https://github.com/stantanasi/streamflix/assets/46174829/fb6103c2-7dab-431d-967e-367dfb31badc)
