### ISSUE TITLE
Videos not launching

### ISSUE THREAD

**Issue by mattstvmedia** [stantanasi/sflix#5]
And coming up with an error message 
ETERNAL BAD

**Comment by stantanasi** [comment]
**The exception `error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT` does not depend on my code.** There's nothing I can do to solve this issue.

The video URL retrieved from the provider is encrypted. The only way to decrypt the URL is to use a secret key available on another GitHub user's repository. To ensure that the key is always valid, it is refreshed regularly.

If the key isn't valid when the video is launched and this error message appears, then there is nothing I can do, you just have to wait for the key to be refreshed.
