### ISSUE TITLE
pls implement continue watching

### ISSUE THREAD

**Issue by ajimal173** [stantanasi/sflix#9]
dear admin,

here i'm using the app from version 1.0.0 little bit complicate track the episodes where we left n continue to play so pls implement "continue watching" option in app it will we easier for to start play series or moves were we left its my humble request to u. then one more request pls notify if update available.

**Comment by stantanasi** [comment]
**This feature was implemented in [Release 1.1.0](https://github.com/stantanasi/sflix/releases/latest).**
When leaving a movie or episode, between 3% and 90% of the video, the app saves its playback position. Returning to that movie or episode, the player will automatically seek to your last position (minus 10 seconds).

If this functionality doesn't work for you, could you please tell me which device are you using with which version of Android, and the steps to reproduce the bug.

**Comment by stantanasi** [comment]
I will soon be implementing a `Continue Watching` category displayed on the homepage where it will be possible to resume movies or episodes that you have already started, directly from the homepage.

After finishing an episode, it will not be possible to directly access the next episode to watch, too complicated to implement. You will still need to navigate through the TV show to watch the next episode.

**Comment by ajimal173** [comment]
> **This feature was implemented in [Release 1.1.0](https://github.com/stantanasi/sflix/releases/latest).** When leaving a movie or episode, between 3% and 90% of the video, the app saves its playback position. Returning to that movie or episode, the player will automatically seek to your last position (minus 10 seconds).
> 
> If this functionality doesn't work for you, could you please tell me which device are you using with which version of Android, and the steps to reproduce the bug.

im using mi box 4k android version 9.0.
sir actually 1.1.0 app not open at first attempt after 5 to 6 attempt then only app opening the dashboard 

now latest version 1.2.0 app open but at first asking 2 option which server to open "all movies" or "sflix" tab 
sflix content not loading still loader loading content not opening, 
all movies also not working showing error like no handshake

note:
still 1.1.0 working but we need to open app atleast 4 to 5 click then only app opening

pls take a look n fix i really unable to watch movies from sflix app

**Comment by stantanasi** [comment]
**Available on [Release 1.2.1](https://github.com/stantanasi/sflix/releases/latest)**
